export type TemplateCategory = '基础' | '代数' | '微积分' | '线性代数' | '概率统计' | '几何' | '物理' | '化学' | '数学建模';

export type TemplateItem = {
  id: string;
  name: string;
  category: TemplateCategory;
  latex: string;
  tags: string[];
};

const entries: Array<[TemplateCategory, string, string, string[]]> = [
  ['基础', '二次方程', 'x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}', ['代数', '根式']],
  ['基础', '欧拉恒等式', 'e^{i\\pi} + 1 = 0', ['复数']],
  ['基础', '二项式定理', '(a+b)^n = \\sum_{k=0}^{n} \\binom{n}{k}a^{n-k}b^k', ['展开']],
  ['基础', '绝对值', '|x| = \\begin{cases}x & x\\ge 0\\\\-x & x<0\\end{cases}', ['分段']],
  ['代数', '等差数列', 'a_n = a_1 + (n-1)d', ['数列']],
  ['代数', '等比数列', 'a_n = a_1q^{n-1}', ['数列']],
  ['代数', '对数换底', '\\log_a b = \\frac{\\log_c b}{\\log_c a}', ['对数']],
  ['代数', '韦达定理', 'x_1+x_2=-\\frac{b}{a},\\quad x_1x_2=\\frac{c}{a}', ['方程']],
  ['微积分', '导数定义', "f'(x)=\\lim_{h\\to0}\\frac{f(x+h)-f(x)}{h}", ['极限']],
  ['微积分', '积分定义', '\\int_a^b f(x)\\,dx = \\lim_{n\\to\\infty}\\sum_{i=1}^n f(x_i^*)\\Delta x', ['定积分']],
  ['微积分', '泰勒展开', 'f(x)=\\sum_{n=0}^{\\infty}\\frac{f^{(n)}(a)}{n!}(x-a)^n', ['级数']],
  ['微积分', '偏导数', '\\frac{\\partial f}{\\partial x},\\quad \\frac{\\partial^2 f}{\\partial x^2}', ['多元']],
  ['线性代数', '矩阵', '\\begin{bmatrix}a & b\\\\c & d\\end{bmatrix}', ['矩阵']],
  ['线性代数', '行列式', '\\det(A)=\\begin{vmatrix}a & b\\\\c & d\\end{vmatrix}=ad-bc', ['矩阵']],
  ['线性代数', '特征方程', '\\det(A-\\lambda I)=0', ['特征值']],
  ['线性代数', '内积', '\\langle u,v\\rangle = \\sum_{i=1}^{n}u_iv_i', ['向量']],
  ['概率统计', '期望', '\\mathbb{E}[X]=\\sum_x x p(x)', ['随机变量']],
  ['概率统计', '正态分布', 'f(x)=\\frac{1}{\\sqrt{2\\pi\\sigma^2}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}', ['分布']],
  ['概率统计', '贝叶斯公式', 'P(A\\mid B)=\\frac{P(B\\mid A)P(A)}{P(B)}', ['条件概率']],
  ['概率统计', '方差', '\\operatorname{Var}(X)=\\mathbb{E}[(X-\\mu)^2]', ['统计量']],
  ['几何', '勾股定理', 'a^2+b^2=c^2', ['三角形']],
  ['几何', '圆方程', '(x-a)^2+(y-b)^2=r^2', ['解析几何']],
  ['几何', '距离公式', 'd=\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}', ['解析几何']],
  ['几何', '球体积', 'V=\\frac{4}{3}\\pi r^3', ['立体几何']],
  ['物理', '质能方程', 'E=mc^2', ['相对论']],
  ['物理', '牛顿第二定律', 'F=ma', ['力学']],
  ['物理', '动量定理', '\\vec p=m\\vec v,\\quad \\vec F=\\frac{d\\vec p}{dt}', ['力学']],
  ['物理', '薛定谔方程', 'i\\hbar\\frac{\\partial}{\\partial t}\\Psi=\\hat H\\Psi', ['量子']],
  ['化学', '理想气体', 'PV=nRT', ['热力学']],
  ['化学', '物质的量浓度', 'c=\\frac{n}{V}', ['溶液']],
  ['化学', '反应速率', 'v=-\\frac{1}{a}\\frac{d[A]}{dt}', ['动力学']],
  ['化学', '酸碱度', '\\mathrm{pH}=-\\log_{10}[H^+]', ['平衡']],
  ['基础', '三角恒等式', '\\sin^2 x+\\cos^2 x=1', ['三角函数']],
  ['基础', '和角公式', '\\sin(a+b)=\\sin a\\cos b+\\cos a\\sin b', ['三角函数']],
  ['代数', '指数法则', 'a^m a^n=a^{m+n},\\quad \\frac{a^m}{a^n}=a^{m-n}', ['指数']],
  ['代数', '复数极坐标', 'z=r(\\cos\\theta+i\\sin\\theta)', ['复数']],
  ['微积分', '牛顿-莱布尼茨公式', '\\int_a^b f(x)\\,dx=F(b)-F(a)', ['定积分']],
  ['微积分', '梯度', '\\nabla f=\\left(\\frac{\\partial f}{\\partial x},\\frac{\\partial f}{\\partial y},\\frac{\\partial f}{\\partial z}\\right)', ['多元']],
  ['微积分', '散度', '\\nabla\\cdot\\vec F=\\frac{\\partial F_x}{\\partial x}+\\frac{\\partial F_y}{\\partial y}+\\frac{\\partial F_z}{\\partial z}', ['向量分析']],
  ['微积分', '拉普拉斯算子', '\\Delta f=\\nabla^2f=\\frac{\\partial^2f}{\\partial x^2}+\\frac{\\partial^2f}{\\partial y^2}', ['偏微分']],
  ['线性代数', '三阶矩阵', '\\begin{bmatrix}a&b&c\\\\d&e&f\\\\g&h&i\\end{bmatrix}', ['矩阵']],
  ['线性代数', '逆矩阵', 'A^{-1}=\\frac{1}{\\det A}\\operatorname{adj}(A)', ['矩阵']],
  ['线性代数', '矩阵乘法', 'C_{ij}=\\sum_{k=1}^{n}A_{ik}B_{kj}', ['矩阵']],
  ['概率统计', '协方差', '\\operatorname{Cov}(X,Y)=\\mathbb{E}[(X-\\mu_X)(Y-\\mu_Y)]', ['统计量']],
  ['概率统计', '相关系数', '\\rho_{XY}=\\frac{\\operatorname{Cov}(X,Y)}{\\sigma_X\\sigma_Y}', ['统计量']],
  ['概率统计', '二项分布', 'P(X=k)=\\binom{n}{k}p^k(1-p)^{n-k}', ['分布']],
  ['概率统计', '泊松分布', 'P(X=k)=\\frac{\\lambda^k e^{-\\lambda}}{k!}', ['分布']],
  ['概率统计', '置信区间', '\\bar{x}\\pm z_{\\alpha/2}\\frac{\\sigma}{\\sqrt n}', ['统计量']],
  ['几何', '椭圆方程', '\\frac{x^2}{a^2}+\\frac{y^2}{b^2}=1', ['解析几何']],
  ['几何', '圆柱体积', 'V=\\pi r^2h', ['立体几何']],
  ['物理', '动能', 'E_k=\\frac{1}{2}mv^2', ['力学']],
  ['物理', '简谐运动', 'x(t)=A\\cos(\\omega t+\\varphi)', ['振动']],
  ['物理', '电场强度', '\\vec E=\\frac{\\vec F}{q}', ['电磁学']],
  ['物理', '波动方程', '\\frac{\\partial^2u}{\\partial t^2}=v^2\\frac{\\partial^2u}{\\partial x^2}', ['波动']],
  ['化学', '能斯特方程', 'E=E^\\circ-\\frac{RT}{nF}\\ln Q', ['电化学']],
  ['化学', '阿伦尼乌斯方程', 'k=Ae^{-\\frac{E_a}{RT}}', ['动力学']],
  ['数学建模', '线性规划目标函数', '\\min_{x}\\;c^\\mathsf{T}x\\quad\\text{s.t.}\\quad Ax\\le b,\\;x\\ge0', ['优化', '规划']],
  ['数学建模', '拉格朗日函数', '\\mathcal{L}(x,\\lambda)=f(x)+\\lambda^\\mathsf{T}g(x)', ['优化', '约束']],
  ['数学建模', 'KKT 条件', '\\nabla f(x)+J_g(x)^\\mathsf{T}\\lambda=0,\\quad g(x)\\le0,\\quad \\lambda\\ge0,\\quad \\lambda_i g_i(x)=0', ['优化']],
  ['数学建模', '梯度下降', 'x_{k+1}=x_k-\\eta_k\\nabla f(x_k)', ['优化', '算法']],
  ['数学建模', '牛顿迭代', 'x_{k+1}=x_k-[\\nabla^2 f(x_k)]^{-1}\\nabla f(x_k)', ['数值优化']],
  ['数学建模', '最小二乘估计', '\\hat{\\beta}=\\arg\\min_{\\beta}\\|y-X\\beta\\|_2^2=(X^\\mathsf{T}X)^{-1}X^\\mathsf{T}y', ['回归']],
  ['数学建模', '岭回归', '\\hat{\\beta}=\\arg\\min_{\\beta}\\{\\|y-X\\beta\\|_2^2+\\lambda\\|\\beta\\|_2^2\\}', ['正则化']],
  ['数学建模', 'Lasso 回归', '\\hat{\\beta}=\\arg\\min_{\\beta}\\{\\|y-X\\beta\\|_2^2+\\lambda\\|\\beta\\|_1\\}', ['特征选择']],
  ['数学建模', '逻辑回归', 'P(y=1\\mid x)=\\sigma(\\beta_0+\\beta^\\mathsf{T}x),\\quad \\sigma(z)=\\frac{1}{1+e^{-z}}', ['分类']],
  ['数学建模', '贝叶斯后验', 'p(\\theta\\mid D)=\\frac{p(D\\mid\\theta)p(\\theta)}{p(D)}', ['统计推断']],
  ['数学建模', '最大似然估计', '\\hat{\\theta}=\\arg\\max_{\\theta}\\prod_{i=1}^{n}p(x_i\\mid\\theta)', ['统计推断']],
  ['数学建模', 'AIC 信息准则', '\\mathrm{AIC}=2k-2\\ln\\hat L', ['模型选择']],
  ['数学建模', '主成分分析', '\\max_{\\|w\\|_2=1}\\;w^\\mathsf{T}Sw', ['降维']],
  ['数学建模', '奇异值分解', 'A=U\\Sigma V^\\mathsf{T}', ['矩阵分解']],
  ['数学建模', '条件数', '\\kappa(A)=\\|A\\|\\,\\|A^{-1}\\|', ['数值分析']],
  ['数学建模', '欧拉方法', 'y_{n+1}=y_n+h f(t_n,y_n)', ['常微分方程']],
  ['数学建模', '四阶 Runge-Kutta', '\\begin{aligned}k_1&=f(t_n,y_n)\\\\k_2&=f(t_n+\\frac h2,y_n+\\frac h2k_1)\\\\y_{n+1}&=y_n+\\frac h6(k_1+2k_2+2k_3+k_4)\\end{aligned}', ['数值计算']],
  ['数学建模', '常微分方程初值问题', '\\frac{dy}{dt}=f(t,y),\\quad y(t_0)=y_0', ['常微分方程']],
  ['数学建模', '扩散方程', '\\frac{\\partial u}{\\partial t}=D\\nabla^2u', ['偏微分方程']],
  ['数学建模', '热传导方程', '\\frac{\\partial u}{\\partial t}=\\alpha\\frac{\\partial^2u}{\\partial x^2}', ['偏微分方程']],
  ['数学建模', '波动方程', '\\frac{\\partial^2u}{\\partial t^2}=c^2\\nabla^2u', ['偏微分方程']],
  ['数学建模', '有限差分格式', '\\frac{u_i^{n+1}-u_i^n}{\\Delta t}=D\\frac{u_{i+1}^n-2u_i^n+u_{i-1}^n}{\\Delta x^2}', ['数值计算']],
  ['数学建模', '马尔可夫转移', '\\pi_{t+1}=\\pi_tP', ['随机过程']],
  ['数学建模', 'PageRank', 'r=\\alpha Mr+(1-\\alpha)\\frac{\\mathbf{1}}{n}', ['网络分析']],
  ['数学建模', 'SIR 模型', '\\frac{dS}{dt}=-\\beta\\frac{SI}{N},\\quad\\frac{dI}{dt}=\\beta\\frac{SI}{N}-\\gamma I', ['传染病模型']],
  ['数学建模', 'Lotka-Volterra 模型', '\\frac{dx}{dt}=\\alpha x-\\beta xy,\\quad\\frac{dy}{dt}=\\delta xy-\\gamma y', ['生态模型']],
  ['数学建模', '排队系统利用率', '\\rho=\\frac{\\lambda}{\\mu}<1', ['排队论']],
  ['数学建模', '运输问题', '\\min\\sum_{i=1}^{m}\\sum_{j=1}^{n}c_{ij}x_{ij}', ['运筹学']],
  ['数学建模', '熵', 'H(X)=-\\sum_x p(x)\\log p(x)', ['信息论']],
  ['数学建模', '交叉熵损失', 'L=-\\sum_{i=1}^{n}y_i\\log\\hat y_i', ['机器学习']],
  ['数学建模', '均方误差', '\\mathrm{MSE}=\\frac1n\\sum_{i=1}^{n}(y_i-\\hat y_i)^2', ['模型评价']],
  ['数学建模', '混淆矩阵准确率', '\\mathrm{Accuracy}=\\frac{TP+TN}{TP+TN+FP+FN}', ['分类评价']]
];

export const BUILT_IN_TEMPLATES: TemplateItem[] = entries.map(([category, name, latex, tags], index) => ({
  id: `built-in-${index + 1}`,
  name,
  category,
  latex,
  tags
}));

export const TEMPLATE_CATEGORIES: TemplateCategory[] = ['基础', '代数', '微积分', '线性代数', '概率统计', '几何', '物理', '化学', '数学建模'];
